version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro    # read-only
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload   # overriding docker command
    env_file:
      - ./.env
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: